[build]
  publish = "dist"
  command = "npm install --legacy-peer-deps && astro build && node postbuild.js"
  
[build.environment]
  NODE_VERSION = "18"
  ASTRO_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
