# BlondePlace Netlify Config (Astro Fix)
[build]
  publish = "blondeplace-blog/dist"
  command = "npm run build-blog && node postbuild.js"
  
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  ASTRO_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  
# Processing
[build.processing]
  skip_processing = false
  
[build.processing.css]
  bundle = true
  minify = true
  
[build.processing.js] 
  bundle = true
  minify = true
  
[build.processing.html]
  pretty_urls = true
  
# Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    
[[headers]]
  for = "/blog/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
# Redirects
[[redirects]]
  from = "/salon"
  to = "https://blondeplace.ru"
  status = 301
  
[[redirects]]
  from = "/services"
  to = "https://blondeplace.ru/#services"
  status = 301

[[redirects]]
  from = "/contact"
  to = "https://blondeplace.ru/#about"
  status = 301
