[build]
  publish = "dist"
  command = "npm install --legacy-peer-deps && astro build && node postbuild.js"
  
[build.environment]
  NODE_VERSION = "18"
  ASTRO_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"

# SECURITY HEADERS (BEST PRACTICES FIX)
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://apis.google.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://images.unsplash.com https://blondeplace.ru; media-src 'self'; connect-src 'self' https://api.indexnow.org; frame-src 'self' https://www.google.com;"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# 🔥 SEO OPTIMIZATION PLUGINS
[[plugins]]
  package = "@netlify/plugin-sitemap"
  
  [plugins.inputs]
    changeFreq = "daily"
    priority = 0.8
    prettyURLs = true
    trailingSlash = false
    
    exclude = [
      "/admin/**",
      "/api/**", 
      "**/*.json",
      "**/*.xml"
    ]

# 🎯 LIGHTHOUSE QUALITY CONTROL
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs]
    fail_deploy_on_score_thresholds = "false"
    
  [plugins.inputs.thresholds]
    performance = 0.90
    seo = 0.95
    accessibility = 0.90
    best-practices = 0.85
    pwa = 0.80