[build]
  # ТОЛЬКО БАЗОВАЯ КОМАНДА БЕЗ ВСЕХ ФЛАГОВ
  command = "npm run build && echo 'Build completed, starting postbuild...' && node postbuild.js"
  publish = "dist"
  
[build.environment]
  # ПРИНУДИТЕЛЬНАЯ УСТАНОВКА NODE.JS 22
  NODE_VERSION = "22"
  
  # ТОЛЬКО ПРОВЕРЕННЫЙ ФЛАГ ПАМЯТИ
  NODE_OPTIONS = "--max-old-space-size=4096"
  
  # ОТКЛЮЧАЕМ ВСЁ ЛИШНЕЕ
  ASTRO_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  
  # ОГРАНИЧИВАЕМ КОЛИЧЕСТВО ПОТОКОВ
  UV_THREADPOOL_SIZE = "2"
  
  # ОТКЛЮЧАЕМ ПРЕДУПРЕЖДЕНИЯ
  NODE_NO_WARNINGS = "1"
  
  # ОТКЛЮЧАЕМ VITE CACHE
  VITE_CACHE_DIR = "false"
  
  # ОТКЛЮЧАЕМ NETLIFY ОПТИМИЗАЦИИ ДЛЯ ЭКОНОМИИ
  NETLIFY_USE_EDGE = "false"

# БЕЗ ПЛАГИНОВ - ТОЛЬКО БАЗОВЫЕ HEADERS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

# БАЗОВОЕ КЕШИРОВАНИЕ СТАТИЧЕСКИХ ФАЙЛОВ
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# ВАЖНЫЕ ФАЙЛЫ
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "application/xml"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "text/plain"

# МИНИМАЛЬНЫЕ РЕДИРЕКТЫ
[[redirects]]
  from = "/blog/index.html"
  to = "/blog/"
  status = 301

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301 