[build]
  # УЛЬТРА-ПРОСТАЯ КОМАНДА БЕЗ ЛИШНИХ ОПЕРАЦИЙ
  command = "astro build && node postbuild.js"
  publish = "dist"

[build.environment]
  # КОНСЕРВАТИВНЫЕ НАСТРОЙКИ
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max-old-space-size=4096 --no-warnings --disable-proto=delete"
  
  # ОТКЛЮЧАЕМ ВСЁ ЛИШНЕЕ
  ASTRO_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  
  # МИНИМИЗИРУЕМ ИСПОЛЬЗОВАНИЕ ПАМЯТИ
  UV_THREADPOOL_SIZE = "2"
  NODE_NO_WARNINGS = "1"

# НЕТ ПЛАГИНОВ - НЕТ ПРОБЛЕМ

# МИНИМАЛЬНЫЕ HEADERS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "application/xml"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "text/plain"

# ОСНОВНЫЕ REDIRECTS
[[redirects]]
  from = "/blog/index.html"
  to = "/blog/"
  status = 301

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301 