name: ALPHA-STRIKE v5.2-RACE-FIXED

on:
  workflow_dispatch:
    inputs:
      target_articles:
        description: 'Количество статей для генерации'
        required: true
        default: '50'
        type: string
      model_choice:
        description: 'Выбор AI модели'
        required: true
        default: 'gemini'
        type: choice
        options:
        - gemini
        - openrouter

jobs:
  alpha-strike-attack:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    strategy:
      max-parallel: 20
      fail-fast: false  # КРИТИЧНО: НЕ отменять остальные jobs при сбое одного
      matrix:
        thread-id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies  
      run: |
        npm install googleapis node-fetch@2.6.7 execa@5.1.1 slugify@1.6.6

    - name: SETUP API KEYS
      run: |
        if [ "${{ github.event.inputs.model_choice }}" = "gemini" ]; then
          KEYS_POOL="${{ secrets.GEMINI_API_KEYS_POOL }}"
          KEY_INDEX=${{ matrix.thread-id }}
          API_KEY=$(echo "$KEYS_POOL" | tr ',' '\n' | sed -n "${KEY_INDEX}p")
          echo "GEMINI_API_KEY_CURRENT=$API_KEY" >> $GITHUB_ENV
          echo "MODEL_CHOICE=gemini" >> $GITHUB_ENV
        else
          KEYS_POOL="${{ secrets.OPENROUTER_API_KEYS_POOL }}"
          KEY_INDEX=${{ matrix.thread-id }}
          API_KEY=$(echo "$KEYS_POOL" | tr ',' '\n' | sed -n "${KEY_INDEX}p")
          echo "OPENROUTER_API_KEY_CURRENT=$API_KEY" >> $GITHUB_ENV
          echo "MODEL_CHOICE=openrouter" >> $GITHUB_ENV
        fi

    - name: ALPHA-STRIKE GENERATION
      run: |
        echo "🎯 ЭСКАДРОН #${{ matrix.thread-id }}: Начинаю Alpha-Strike атаку!"
        export THREAD_ID=${{ matrix.thread-id }}
        export TARGET_ARTICLES=${{ github.event.inputs.target_articles }}
        node alpha-factory.js

    - name: SUPER-SAFE GIT OPERATIONS (RACE-PROOF)
      run: |
        # Настройка Git
        git config --local user.email "action@github.com"
        git config --local user.name "Alpha-Strike Bot"
        
        # УСИЛЕННАЯ ЗАЩИТА ОТ RACE CONDITIONS
        RANDOM_DELAY=$((RANDOM % 90 + 30))  # 30-120 секунд вместо 5-35
        echo "🛡️ Thread ${{ matrix.thread-id }}: ЗАЩИТА ОТ RACE - ждём ${RANDOM_DELAY}s..."
        sleep ${RANDOM_DELAY}
        
        # СУПЕР-RETRY МЕХАНИЗМ (10 попыток вместо 5)
        for attempt in {1..10}; do
          echo "🔄 Thread ${{ matrix.thread-id }}: Git push попытка $attempt/10"
          
          # Стратегия безопасного push
          git stash push -m "temp-stash-${{ matrix.thread-id }}-$attempt" || true
          git pull --rebase origin main || true
          git stash pop || true
          
          # Добавляем изменения
          git add src/content/posts/ || true
          
          # Проверяем есть ли что коммитить
          if git diff --staged --quiet; then
            echo "✅ Thread ${{ matrix.thread-id }}: Нет изменений для commit"
            break
          fi
          
          # Коммит с уникальным сообщением
          git commit -m "🎯 Alpha-Strike v5.2: Thread ${{ matrix.thread-id }} - Attempt $attempt - $(date)" || true
          
          # Пробуем push
          if git push origin main; then
            echo "✅ Thread ${{ matrix.thread-id }}: Git push успешен на попытке $attempt!"
            break
          else
            echo "⚠️ Thread ${{ matrix.thread-id }}: Git push неудачен, попытка $attempt"
            if [ $attempt -eq 10 ]; then
              echo "❌ Thread ${{ matrix.thread-id }}: Все 10 попыток исчерпаны"
              exit 1
            fi
            # Дополнительная задержка между попытками
            sleep $((RANDOM % 30 + 10))
          fi
        done

    - name: REPORT GENERATION  
      run: |
        echo "✅ ЭСКАДРОН #${{ matrix.thread-id }}: Alpha-Strike миссия завершена!"
        echo "🎯 Model: ${{ github.event.inputs.model_choice }}"
        echo "📊 Target articles: ${{ github.event.inputs.target_articles }}"

  quality-control:
    needs: alpha-strike-attack
    runs-on: ubuntu-latest
    if: always()  # Запускаем даже если некоторые jobs провалились
    steps:
    - name: Checkout repository  
      uses: actions/checkout@v4

    - name: QUALITY CONTROL
      run: |
        echo "🔍 КОНТРОЛЬ КАЧЕСТВА ALPHA-STRIKE v5.2"
        echo ""
        echo "📊 СТАТИСТИКА СОЗДАННЫХ СТАТЕЙ:"
        find src/content/posts -name "post*.md" -newer .git/logs/HEAD | wc -l || echo "0"
        echo ""
        echo "🔗 ПРЯМЫЕ ССЫЛКИ НА НОВЫЕ СТАТЬИ:"
        find src/content/posts -name "post*.md" -newer .git/logs/HEAD | head -10 | while read file; do
          filename=$(basename "$file" .md)
          echo "  📄 https://blondeplace.netlify.app/blog/$filename/"
        done

  final-report:
    needs: [alpha-strike-attack, quality-control]
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: FINAL REPORT
      run: |
        echo "🎯 ФИНАЛЬНЫЙ ОТЧЁТ ALPHA-STRIKE v5.2-RACE-FIXED"
        echo ""
        echo "✅ МИССИЯ ЗАВЕРШЕНА С УЛУЧШЕННОЙ ЗАЩИТОЙ ОТ RACE CONDITIONS"
        echo "🛡️ Задержки увеличены до 30-120 секунд"
        echo "🔄 Retry попытки увеличены до 10"
        echo "🎯 Fail-fast отключён - все потоки работают независимо"
        echo ""
        echo "🚀 ALPHA-STRIKE ГОТОВ К ДОМИНИРОВАНИЮ!" 