name: 🚀 BlondePlace Beauty Factory (Atomic Lock)

on:
  workflow_dispatch:
    inputs:
      batch_size_per_thread:
        description: 'Сколько статей генерировать КАЖДЫМ потоком?'
        required: true
        default: '5'
      threads:
        description: 'Сколько потоков запустить ОДНОВРЕМЕННО (1-20)?'
        required: true
        default: '5'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - name: Create thread matrix
        id: set_matrix
        run: |
          MAX_THREADS=20
          REQUESTED_THREADS=${{ github.event.inputs.threads }}
          
          if (( REQUESTED_THREADS > MAX_THREADS )); then
            echo "::warning::Запрошено больше потоков (${REQUESTED_THREADS}), чем доступно ключей (${MAX_THREADS}). Будет использовано ${MAX_THREADS}."
            REQUESTED_THREADS=$MAX_THREADS
          fi

          MATRIX=$(jq -cn --argjson n "$REQUESTED_THREADS" '[range(1; $n + 1)]')
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  generate_and_publish:
    needs: prepare
    permissions:
      contents: write
      
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        thread: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
      - name: ⬇️ Checkout repo (Thread ${{ matrix.thread }})
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: ⚙️ Setup Node.js (Thread ${{ matrix.thread }})
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Install dependencies (Thread ${{ matrix.thread }})
        run: npm install

      - name: 🔑 Set API Key for Thread ${{ matrix.thread }}
        id: set_key
        run: |
          API_KEYS="${{ secrets.GEMINI_API_KEYS_POOL }}"
          CURRENT_KEY=$(echo "$API_KEYS" | sed -n '${{ matrix.thread }}p' | tr -d '\r')
          if [[ -z "$CURRENT_KEY" ]]; then
            echo "::error::Не удалось извлечь API-ключ для потока #${{ matrix.thread }}. Проверьте секрет GEMINI_API_KEYS_POOL."
            exit 1
          fi
          echo "key=$CURRENT_KEY" >> $GITHUB_OUTPUT

      - name: 🏭 Run Factory & 📢 Publish & Notify (Thread ${{ matrix.thread }})
        env:
          GEMINI_API_KEY_CURRENT: ${{ steps.set_key.outputs.key }}
          BATCH_SIZE: ${{ github.event.inputs.batch_size_per_thread }}
          TOTAL_THREADS: ${{ github.event.inputs.threads }}
          THREAD_ID: ${{ matrix.thread }}
        run: |
          git config --global user.name 'BlondePlace Beauty Bot'
          git config --global user.email 'beauty-bot@blondeplace.ru'
          git config --global pull.rebase true
          
          echo "--- BEAUTY ПОТОК #${{ matrix.thread }}: Начинаю генерацию beauty контента ---"
          
          npm run factory
          
          if [[ -z $(git status --porcelain) ]]; then
            echo "✅ BEAUTY ПОТОК #${{ matrix.thread }}: Новых beauty статей для этого потока не найдено. Beauty миссия завершена."
            exit 0
          fi

          echo "🔥 BEAUTY ПОТОК #${{ matrix.thread }}: Обнаружены новые файлы. Начинаю процедуру публикации..."
          
          MAX_RETRIES=5
          RETRY_DELAY=5
          for ((i=1; i<=MAX_RETRIES; i++)); do
            git pull --rebase
            git add src/content/posts/*.md
            # Используем --allow-empty чтобы коммит создавался, даже если файлы идентичны после pull
            git commit --allow-empty -m "🚀 Авто-публикация: пачка от Эскадрона №${{ matrix.thread }}"
            
            if git push; then
              echo "✅ Публикация прошла успешно с попытки №$i."
              break
            else
              if [ "$i" -eq "$MAX_RETRIES" ]; then
                echo "::error::Не удалось опубликовать изменения после $MAX_RETRIES попыток."
                exit 1
              fi
              echo "[!] Конфликт! Попытка №$i не удалась. Жду ${RETRY_DELAY}с и пробую снова..."
              # Перед следующей попыткой отменяем неудачный коммит
              git reset --hard HEAD~1
              sleep $RETRY_DELAY
            fi
          done
          
          commit_after=$(git rev-parse HEAD)
          commit_before=$(git rev-parse HEAD~1)
          
          NEW_FILES=$(git diff --name-only $commit_before $commit_after -- 'src/content/posts/*.md')
          
          if [[ -n "$NEW_FILES" ]]; then
            echo "📢 BEAUTY ПОТОК #${{ matrix.thread }}: Подготовка уведомления для IndexNow..."
            API_KEY="d1b055ab1eb146d892169bbb2c96550e"
            HOST="butlerspb-blog.netlify.app"

            URL_JSON_ARRAY=$(for file in $NEW_FILES; do slug=$(basename "$file" .md); echo "https://butlerspb-blog.netlify.app/blog/${slug}/"; done | jq -R . | jq -s .)

            JSON_PAYLOAD=$(jq -n \
                            --arg host "$HOST" \
                            --arg key "$API_KEY" \
                            --argjson urls "$URL_JSON_ARRAY" \
                            '{host: $host, key: $key, urlList: $urls}')
            
            echo "--- Диагностика пакета для IndexNow (Эскадрон №${{ matrix.thread }}) ---"
            echo "$JSON_PAYLOAD"
            echo "--- Конец диагностики ---"
            
            curl -X POST "https://yandex.com/indexnow" -H "Content-Type: application/json; charset=utf-8" -d "$JSON_PAYLOAD"
            curl -X POST "https://www.bing.com/indexnow" -H "Content-Type: application/json; charset=utf-8" -d "$JSON_PAYLOAD"
          fi
          
          echo -e "\n✅ BEAUTY ПОТОК #${{ matrix.thread }}: Миссия успешно завершена." 